---
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"

remi_repo_url: "http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
remi_repo_gpg_key_url: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"

php_version: php

base_packages:
  - bc
  - screen
  - vim-enhanced
  - zlib-devel
  - gcc
  - gcc-c++
  - make
  - tcpdump
  - lsof
  - wget
  - telnet
  - pcre-devel
  - screen
  - MySQL-python
  - yum-utils  

base_epel_packages:
  - atop
  - pwgen
  - libmcrypt
  - redis

php72_packages:
  - php
  - php-common
  - php-iconv
  - php-mbstring
  - php-curl
  - php-openssl
  - php-tokenizer
  - php-xmlrpc
  - php-soap
  - php-ctype
  - php-gd
  - php-xml
  - php-intl
  - php-json
  - php-pecl-redis
  - php-opcache
  - php-mysqli

sysctls:
  - { name: vm.swappiness, value: 1 }
  - { name: vm.overcommit_memory, value: 1 }
  - { name: vm.panic_on_oom, value: 1 }
  - { name: kernel.panic, value: 5 }

apache_daemon: httpd
apache_daemon_path: /usr/sbin/
apache_server_root: /etc/httpd
apache_conf_path: /etc/httpd/conf.d

apache_vhosts_version: "2.4"

__apache_packages:
  - httpd
  - httpd-devel  

apache_create_vhosts: "true"
apache_vhosts_filename: "vhosts.conf"
apache_vhosts_template: "vhosts.conf.j2"
apache_remove_default_vhost: "false"

apache_ports_configuration_items:
  - regexp: "^Listen "
    line: "Listen 80"


apache_vhosts:
  - {servername: "charitylearning.org", documentroot: "/var/www/charitylearning.org/files"}